<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZenwtkK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZenwtkK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZenwtkK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZenwtkK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZenwtkK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZenwtkK',
    'container.build_id' => '08bef883',
    'container.build_time' => 1578396741,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZenwtkK');
