<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKicxHF9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKicxHF9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKicxHF9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKicxHF9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKicxHF9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KicxHF9',
    'container.build_id' => '9c26d65f',
    'container.build_time' => 1578425690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKicxHF9');
