version: "2"
services:
  database:
    container_name: database
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=symfony
      
  webserver:
    container_name: webserver
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "8181:80"
    volumes:
      - ./app:/var/www/html
    links:
      - database:database

  dependencies:
    container_name: dependencies
    build: 
      context: .
      dockerfile: ./docker/dependencies/Dockerfile
    volumes:
      - ./app:/var/www/html
    links:
      - database:database