#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout
  methods: GET

register:
  path: /register
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /register/individual
    permanent: true